CoeusProject/Models/Video.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Data.Entity;
using CoeusProject.Facade;

namespace CoeusProject.Models
{
    public class Video
    {
        [Key]
        public Int32 IdVideo { get; set; }

        [Required]
        [StringLength(4096)]
        public String TxUrl { get; set; }

        [Required]
        [StringLength(4096)]
        public string TxUrlPoster { get; set; }

        [Required]
        [ForeignKey("Objeto")]
        public Int32 IdObjeto { get; set; }
        public virtual Objeto Objeto { get; set; }

        public Video Encrypt(CoeusProjectContext Context = null)
        {
            if (Context == null)
            {
                Context = new CoeusProjectContext();
            }

            if (this.Objeto == null)
            {
                this.Objeto = Context.Objetos.Where(o => o.IdObjeto == this.IdObjeto).Include(o => o.Salt).FirstOrDefault();
            }

            if (this.Objeto.Salt == null)
            {
                this.Objeto.Salt = Context.Salt.Where(s => s.IdSalt == this.Objeto.IdSalt).FirstOrDefault();
            }

            this.Objeto.Encrypt(Context);
            this.TxUrl = SecurityFacade.Encrypt(this.TxUrl, this.Objeto.Salt.BtSalt);

            return this;
        }

        public Video Decrypt(CoeusProjectContext Context = null)
        {
            if (Context == null)
            {
                Context = new CoeusProjectContext();
            }

            if (this.Objeto == null)
            {
                this.Objeto = Context.Objetos.Where(o => o.IdObjeto == this.IdObjeto).Include(o => o.Salt).FirstOrDefault();
            }

            if (this.Objeto.Salt == null)
            {
                this.Objeto.Salt = Context.Salt.Where(s => s.IdSalt == this.Objeto.IdSalt).FirstOrDefault();
            }

            this.Objeto.Decrypt(Context);
            this.TxUrl = SecurityFacade.Decrypt(this.TxUrl, this.Objeto.Salt.BtSalt);
            return this;
        }

    }
}

CoeusProject/Controllers/FileController.cs
using CoeusProject.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoeusProject.Controllers
{
    public class FileController : Controller
    {
        public ActionResult SaveFile(HttpPostedFileBase file, String nmFile)
        {
            DoSaveFile(file, nmFile);
            return Content("");
        }

        public ActionResult SavePoster(HttpPostedFileBase poster, String nmFile)
        {
            DoSaveFile(poster, nmFile);
            return Content("");
        }

        private void DoSaveFile(HttpPostedFileBase file, String nmFile)
        {
            if (file != null)
            {
                String extension = Path.GetExtension(file.FileName);

                String physicalPath = Path.Combine(Server.MapPath("~/User_Data"), (nmFile + extension));

                if (System.IO.File.Exists(physicalPath))
                {
                    System.IO.File.Delete(physicalPath);
                }

                file.SaveAs(physicalPath);
            }
        }

        public String FormatImage(String nmFoto)
        {
            String physicalPath = Path.Combine(Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "User_Data"), nmFoto);

            if (!System.IO.File.Exists(physicalPath))
            {
                return String.Empty;
            }

            Image resizedImage = ResizeImage(physicalPath, new Size(80, 80));
            System.IO.File.Delete(physicalPath);
            physicalPath = Path.ChangeExtension(physicalPath, "png");
            resizedImage.Save(physicalPath, ImageFormat.Png);

            Image thumb = ResizeImage(physicalPath, new Size(32, 32));
            String thumbPath = physicalPath.Replace(".png", "-thumb.png");

            if (System.IO.File.Exists(thumbPath))
            {
                System.IO.File.Delete(thumbPath);
            }

            thumb.Save(thumbPath, ImageFormat.Png);
            return Path.ChangeExtension(nmFoto, "png");
        }

        public String FormatPoster(String nmPoster)
        {
            String physicalPath = Path.Combine(Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "User_Data"), nmPoster);

            if (!System.IO.File.Exists(physicalPath))
            {
                return String.Empty;
            }

            Image resizedImage = ResizeImage(physicalPath, new Size(400, 225));
            System.IO.File.Delete(physicalPath);
            physicalPath = Path.ChangeExtension(physicalPath, "png");
            resizedImage.Save(physicalPath, ImageFormat.Png);

            return Path.ChangeExtension(nmPoster, "png");
        }

        private Image ResizeImage(String path, Size size)
        {
            Stream imageStream = new FileStream(path, FileMode.Open);

            Image resizedImage = (Image)(new Bitmap(Image.FromStream(imageStream), size));
            imageStream.Close();
            imageStream.Dispose();

            return resizedImage;
        }

        public static void RemoveFile(String fileName)
        {
            String physicalPath = Path.Combine(Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "User_Data"), fileName);

            if (System.IO.File.Exists(physicalPath))
            {
                System.IO.File.Delete(physicalPath);
            }
        }

        public void CleanImages(CoeusProjectContext Context = null)
        {
            if (Context == null) Context = new CoeusProjectContext();

            Int32 idLastImage = Sequence.GetSequence("foto", Context);
            Int32 idLastUserVideoImage = 0;

            Usuario lastUser = Context.Usuarios.OrderByDescending(u => u.NmFoto).FirstOrDefault();
            if (lastUser == null) return;

            idLastUserVideoImage = Convert.ToInt32(lastUser.NmFoto.Replace(".png", "").Replace(".jpg", "").Replace(".bmp", ""));

            Video lastVideo = Context.Videos.OrderByDescending(v => v.TxUrlPoster).FirstOrDefault();
            if (lastVideo != null)
            {
                Int32 idPoster = Convert.ToInt32(lastVideo.TxUrlPoster.Replace(".png","").Replace(".jpg","").Replace(".bmp", ""));

                if (idPoster > idLastUserVideoImage) idLastUserVideoImage = idPoster;
            }

            for (Int32 i = idLastUserVideoImage; i < idLastImage; i++)
            {
                String LPath = Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "User_Data");
                
                String nmImgFile = Path.Combine(LPath, (i.ToString() + ".png"));
                if (System.IO.File.Exists(nmImgFile))
                {
                    System.IO.File.Delete(nmImgFile);
                    continue;
                }

                nmImgFile = Path.Combine(LPath, (i.ToString() + ".jpg"));
                if (System.IO.File.Exists(nmImgFile))
                {
                    System.IO.File.Delete(nmImgFile);
                    continue;
                }

                nmImgFile = Path.Combine(LPath, (i.ToString() + ".bmp"));
                if (System.IO.File.Exists(nmImgFile))
                {
                    System.IO.File.Delete(nmImgFile);
                    continue;
                }
            }

            Sequence.ResetSequence("foto", (idLastUserVideoImage + 1), Context);
        }
    }
}

CoeusProject/Controllers/SeguidorController.cs
using CoeusProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using CoeusProject.Facade;

namespace CoeusProject.Controllers
{
    public class SeguidorController : Controller
    {
        CoeusProjectContext _context = new CoeusProjectContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Follow(Int32 idObjeto)
        {
            Objeto objeto = _context.Objetos.Where(o => o.IdObjeto == idObjeto).FirstOrDefault();
            if (objeto == null) return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Objeto não encontrado");

            Usuario usuario = _context.Usuarios.Include(u=>u.Seguidores).Where(u => u.IdUsuario == objeto.IdUsuario).FirstOrDefault();
            if (usuario == null) return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Usuário não encontrado");

            if (usuario.Seguidores == null) usuario.Seguidores = new List<Usuario>();

            Usuario usuarioLogado = AccountFacade.GetLoggedInUser();

            if (usuario.Seguidores.Where(s => s.IdUsuario == usuarioLogado.IdUsuario).Count() > 0) 
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Você já segue essa pessoa");

            usuario.Seguidores.Add(_context.Usuarios.Where(u => u.IdUsuario == usuarioLogado.IdUsuario).FirstOrDefault());

            _context.Entry(usuario).State = EntityState.Modified;
            _context.SaveChanges();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult GetFollowersIndex(Int32 idUsuario)
        {
            return View("_SeguidorPartial", GetFollowers(idUsuario));
        }

        public ActionResult GetFollowingIndex(Int32 idUsuario)
        {
            return View("_SeguidorPartial", GetFollowing(idUsuario));
        }

        private List<Usuario> GetFollowers(Int32 idUsuario)
        {
            IQueryable<Usuario> usuarios = _context.Usuarios.Where(u => u.IdUsuario == idUsuario)
                                            .Include(u=>u.Salt)
                                            .Include(u => u.Seguidores).SelectMany(u => u.Seguidores);

            List<Usuario> usuariosList = usuarios.ToList();

            return usuariosList.Select(u => new Usuario 
            {
                IdUsuario = u.IdUsuario,
                NmPessoa = u.NmPessoa,
                SnPessoa = u.SnPessoa,
                NmFoto = u.NmThumbFoto,
                TxEmail = u.TxEmail,
                IdSalt = u.IdSalt
            }).Decrypt(_context);
        }

        private List<Usuario> GetFollowing(Int32 idUsuario)
        {
            IQueryable<Usuario> usuarios = _context.Usuarios.Include(u => u.Salt).Where(u => u.Seguidores.Any(s => s.IdUsuario == idUsuario));

            List<Usuario> usuariosList = usuarios.ToList();

            return usuariosList.Select(u => new Usuario
            {
                IdUsuario = u.IdUsuario,
                NmPessoa = u.NmPessoa,
                SnPessoa = u.SnPessoa,
                NmFoto = u.NmThumbFoto,
                TxEmail = u.TxEmail,
                IdSalt = u.IdSalt
            }).Decrypt(_context);
        }
    }
}

CoeusProject/Views/Video/MainVideos.cshtml
@model int
@using Kendo.Mvc.UI
@{Layout = null;}
<script>
    function gridVideos_Data() {
        return { idUsuario: '@Model' };
    }

    function gridMainVideos_Remove(e) {
        setTimeout(function () {
            $('#gridVideos').data('kendoGrid').dataSource.read();
        }, 1000);
    }
</script>

<div style="margin-top: 45px">
    @(Html.Kendo().Grid<CoeusProject.Models.Video>()
        .Name("gridMainVideos")
        .DataSource(dt => dt.Ajax().Read(r => r.Action("AjaxReadVideos", "Video").Data("gridVideos_Data"))
            .Model(model => model.Id("IdVideo"))
            .Destroy("Delete", "Video")
        )
        .Selectable(select => select.Mode(GridSelectionMode.Single))
        .Columns(c =>
        {
            c.Bound(m => m.Objeto.NmObjeto).Title("Vídeos de " + (new CoeusProject.Models.CoeusProjectContext().Usuarios.Where(u => u.IdUsuario == Model)
                .FirstOrDefault().Decrypt().NmPessoa));
            c.Bound(m => m.Objeto.QtAcessos).Title("Quantidade de Acessos").Width(50).HeaderHtmlAttributes(new { @style = "font-size: 10pt" });
            c.Bound(m => m.Objeto.VlMediaAvaliacaoCalc).Title("Avaliação Média").Width(50).HeaderHtmlAttributes(new { @style = "font-size: 10pt" });
            c.Command(command => command.Destroy().Text(" ")).Width(20);
        })
        .Editable(e => e.DisplayDeleteConfirmation(false))
        .Events(e => e.Remove("gridMainVideos_Remove"))
    )
</div>

<script>
    $(document).ready(function () {
        $("#gridMainVideos").on("dblclick", "tr.k-state-selected", function () {
            var grid = $("#gridMainVideos").data("kendoGrid");
            var selectedItem = grid.dataItem(grid.select());
            EditVideo(selectedItem.IdVideo);
        });
    })
</script>

CoeusProject/Views/Video/_VideoEditPartial.cshtml
@model CoeusProject.Models.Video
@using Kendo.Mvc.UI
@{Layout = null;}

<style>
    .k-upload {
        display: inline-block;
        width: 300px;
        height: 0;
        vertical-align: top;
    }

    .k-dropzone {
        height: 0;
    }
</style>

<script>
    function btnVoltarMainVideos_Click(e) {
        $('#divContent').load('@Url.Action("GetMainVideos", "Video")', { idUsuario: idDonoVideo });
        $('#divInteressesVideo').html('');
    }

    function btnEditVideo_Click(e) {
        $('#txNomeObjeto').val($('#hidNmObjeto').val());
        $('#txDescricaoObjeto').val($('#hidTxDescricao').val());

        $('#wndVideoEdit').data('kendoWindow').center().open();
    }

    function btnSalvarObjeto_Click(e) {
        var idVideoEdit = parseInt($('#idVideoEdit').val());

        function VideoEditPartial_Close() {
            $('#wndVideoEdit').data('kendoWindow').close();
            $('#divContent').load('@Url.Action("GetMainVideos", "Video")', { idUsuario: idDonoVideo });
            $('#gridVideos').data('kendoGrid').dataSource.read();
            $('#divInteressesVideo').html('');
        }

        if (idVideoEdit) {
            $.ajaxPost('@Url.Action("Edit","Video")', {
                idVideo: idVideoEdit,
                nmObjeto: $('#txNomeObjetoVideo').val(),
                txUrl: $('#TxUrl').val() + extension,
                txUrlPoster: $('#TxUrlPoster').val() + extensionPoster,
                tags: interesses
            }, null, VideoEditPartial_Close);
        } else {
            $.ajaxPost('@Url.Action("Create","Video")', {
                nmObjeto: $('#txNomeObjetoVideo').val(),
                txDescricao: $('#txDescricaoObjetoVideo').val(),
                txUrl: $('#TxUrl').val() + extension,
                txUrlPoster: $('#TxUrlPoster').val() + extensionPoster,
                tags: interesses
            }, null, VideoEditPartial_Close);
        }
    }

    var extension;
    function Video_Select(e) {
        if (e.files[0].extension != ".mp4" && e.files[0].extension != ".webm" && e.files[0].extension != ".ogg") {
            e.preventDefault();
            kendoAlert('Apenas vídeos nos formatos mp4, ogg ou webm são aceitos');
        }
    }

    function Video_Upload(e) {
        e.data = { nmFile: '@Model.TxUrl' };
    }

    function Video_Success(e) {
        extension = e.files[0].extension;
    }


    var extensionPoster = ".png";
    function Poster_Select(e) {
        if (e.files[0].extension != ".png" && e.files[0].extension != ".jpg" && e.files[0].extension != ".bmp") {
            e.preventDefault();
            kendoAlert('Apenas imagens nos formatos png, jpg ou bmp são aceitas');
        }
    }

    function Poster_Upload(e) {
        e.data = { nmFile: '@Model.TxUrlPoster' };
    }

    function Poster_Success(e) {
        extensionPoster = e.files[0].extension;
    }

    $(document).ready(function () {
        if ($('#divVideoPopup').length > 0) { $('#divVideoPopup').html(''); }
        $('#divVideoPopup').load('@Url.Action("GetObjetoPopup", "Video")');

        $('#btnCancelarEditVideo').kendoTooltip({
            position: 'bottom',
            content: 'Cancelar'
        });

        $('#btnEditVideo').kendoTooltip({
            position: 'bottom',
            content: 'Salvar'
        });

        $('#divInteressesVideo').load('@Url.Action("GetInteressePartial", "Interesse")');
    });
</script>

@Html.HiddenFor(m => m.TxUrl)
@Html.HiddenFor(m => m.TxUrlPoster)
@Html.HiddenFor(m => m.IdVideo, new { @id = "idVideoEdit" })
@Html.HiddenFor(m => m.Objeto.NmObjeto, new { @id = "hidNmObjeto" })
@Html.HiddenFor(m => m.Objeto.TxDescricao, new { @id = "hidTxDescricao" })

@{
    if (Model == null || Model.IdVideo == 0)
    {
        @:<h3 style="margin: 3px 0 0 0; position: absolute; top: 20px; left: 0">Novo Vídeo</h3>
    }
    else
    {
        @:<h3 style="margin: 3px 0 0 0; position: absolute; top: 20px; left: 0">@Model.Objeto.NmObjeto</h3>
    }
}

<div class="k-header" style="height: 50px; position:absolute; top: 45px; left: 0; right: 0">
    <div style="margin-top: 10px; display: inline-block">
        @(Html.Kendo().Button().Name("btnVoltarMainVideos")
            .Content("<img src='Images/undo.png' width='16' height='16' />")
            .HtmlAttributes(new { @type = "button" })
            .Events(e => e.Click("btnVoltarMainVideos_Click"))
        )

        @(Html.Kendo().Button().Name("btnEditVideo")
            .Content("<img src='Images/saveAs.png' width='16' height='16' />")
            .HtmlAttributes(new { @type = "button" })
            .Events(e => e.Click("btnEditVideo_Click"))
        )
    </div>

    @(Html.Kendo().Upload()
        .Name("file")
        .Multiple(false)
        .Async(async => async
            .SaveUrl(Url.Action("SaveFile", "File"))
            .AutoUpload(true)
        )
        .Messages(m => m.Select("Selecionar Vídeo"))
        .HtmlAttributes(new { @style = "width: 200px" })
        .ShowFileList(false)
        .Events(e => e
            .Select("Video_Select")
            .Upload("Video_Upload")
            .Success("Video_Success")
        )
    )

    @(Html.Kendo().Upload()
        .Name("poster")
        .Multiple(false)
        .Async(async => async
            .SaveUrl(Url.Action("SavePoster", "File"))
            .AutoUpload(true)
        )
        .Messages(m => m.Select("Selecionar Poster"))
        .ShowFileList(false)
        .Events(e => e
            .Select("Poster_Select")
            .Upload("Poster_Upload")
            .Success("Poster_Success")
        )
    )

</div>

@{Html.Kendo().Window().Name("wndVideoEdit")
    .Content("<div id='divVideoPopup'></div>")
    .Visible(false)
    .Title("Edição")
    .Modal(true)
    .Resizable(r => r.Enabled(false))
    .Render();
}

CoeusProject/Views/Video/_VideoWatchPartial.cshtml
@model CoeusProject.Models.Video
@using Kendo.Mvc.UI
@{Layout = null;}

<link href="~/Content/video-js.css" rel="stylesheet" />
<script src="~/Scripts/video.js"></script>

<style type="text/css">
    #divAvaliacao > label {
        display: inline-block;
        margin-right: 5px;
    }

        #divAvaliacao > label > span {
            font-weight: bold;
        }

        #divAvaliacao > label > input {
            visibility: hidden;
            position: absolute;
        }

            #divAvaliacao > label > input + span {
                cursor: pointer;
                border: 2px solid transparent;
            }

            #divAvaliacao > label > input:checked + span {
                border: 3px solid;
                border-radius: 5px;
            }

            #divAvaliacao > label > input[class=rbtnAvaliacaoAv1]:checked + span {
                border-color: #f00;
            }

            #divAvaliacao > label > input[class=rbtnAvaliacaoAv2]:checked + span {
                border-color: #fb4;
            }

            #divAvaliacao > label > input[class=rbtnAvaliacaoAv3]:checked + span {
                border-color: #ff0;
            }

            #divAvaliacao > label > input[class=rbtnAvaliacaoAv4]:checked + span {
                border-color: #af4;
            }

            #divAvaliacao > label > input[class=rbtnAvaliacaoAv5]:checked + span {
                border-color: #0f0;
            }
</style>

<script>
    function btnVoltarMainVideos_Click(e) {
        $('#divContent').load('@Url.Action("GetMainVideos", "Video")', { idUsuario: idDonoVideo });
    }

    var showingFollowMenu;
    $(document).ready(function () {
        JoinObjectChat('@Model.IdObjeto');

        showingFollowMenu = false;
        @{if ((Model!= null && Model.IdVideo > 0) && (Model.Objeto.IdUsuario != CoeusProject.Facade.AccountFacade.GetLoggedInUser().IdUsuario)){<text>
        $.get('@Url.Action("GetUsuarioByObjeto", "Account")', { idObjeto: '@Model.IdObjeto' }, function (data) {
            $.get('@Url.Action("GetUsuarioRanking", "Account")?idUsuario=@Model.Objeto.IdUsuario', {}, function (rankOwner) {
                $('#spnCreator').html("<div id='divOwnerVideo' style='display:inline-block; cursor: pointer'><img src='~/User_Data/" + data.NmThumbFoto +
                    "'/></div><div style='float:right; text-align: right'><span>" + data.NmPessoa + "</span><br /><span>Rank: " +
                    rankOwner + "</span></div>");

                $('#divOwnerVideo').click(function () {
                    if ($('#divFollowCreator').length > 0) {
                        $('#divFollowCreator').remove();
                    }

                    if (!showingFollowMenu) {
                        $('#spnCreator').append('<div id="divFollowCreator" ' +
                            'style="position: absolute; top: 40px; right: 5px; width: 160px; text-align: left;' +
                            'z-index: 9999; background-color: #AAA; cursor: pointer" onclick = "divFollowCreator_Click()">' +
                            'Seguir</div>');
                    }
                    showingFollowMenu = !showingFollowMenu;
                });
            });
        });
        </text>}}
    });

    function divFollowCreator_Click() {
        $.ajaxPost('@Url.Action("Follow", "Seguidor")', { idObjeto: '@Model.IdObjeto' }, false, function () {
            $('#divFollowCreator').remove();
        });
    }

    function rtbAvaliacao_Click(e) {
        if (e.length > 0) {
            var element = e[0];
            if (element.checked) {
                $.ajaxPost('@Url.Action("Avaliacao", "Video")', {
                    idVideo: '@Model.IdVideo',
                    noAvaliacao: element.value
                }, false, function () { });
            }
        }
    }
</script>


<div class="k-header" style="height: 30px; margin-top: 45px">
    @(Html.Kendo().Button().Name("btnVoltarMainVideos")
            .Content("<img src='Images/undo.png' width='16' height='16' />")
            .HtmlAttributes(new { @type = "button", @style = "float: left" })
            .Events(e => e.Click("btnVoltarMainVideos_Click"))
    )
    <h3 style="margin: 3px 0 0 0; position: absolute; top: 20px; left: 0">@Model.Objeto.NmObjeto</h3>
    @{if (Model != null && Model.IdVideo > 0)
    {
        <span id="spnCreator" style="position: absolute; top: 5px; right: 0; height:44px; width:200px"></span>
    }}
</div>

<div style="position: absolute; top: 80px; left: 10%">
    <video id="vidVideo" class="video-js vjs-default-skin" controls preload="none" width="400" height="225"
           poster="~/User_Data/@Model.TxUrlPoster"
           data-setup="{}">
        <source src="~/User_Data/@Model.TxUrl" type='video/mp4' />
        <source src="~/User_Data/@Model.TxUrl" type='video/3gpp' />
        <source src="~/User_Data/@Model.TxUrl" type='video/m4v' />
        <source src="~/User_Data/@Model.TxUrl" type='video/mpeg' />
        <source src="~/User_Data/@Model.TxUrl" type='video/ogg' />
        <source src="~/User_Data/@Model.TxUrl" type='video/quicktime' />
        <source src="~/User_Data/@Model.TxUrl" type='video/webm' />
        <source src="~/User_Data/@Model.TxUrl" type='video/x-ms-wmv' />

        <p class="vjs-no-js">Para assistir à este vídeo, habilite a execução de JavaScript e considere atualizar seu web browser para um <a href="http://videojs.com/html5-video-support/" target="_blank">que suporte vídeos HTML5</a></p>
    </video>
</div>

<div style="position: absolute; bottom: 0; left: 20px; right: 20px; height: 100px; overflow:auto">
    @Model.Objeto.TxDescricao

    @{if (Model.Objeto.IdUsuario != CoeusProject.Facade.AccountFacade.GetLoggedInUser().IdUsuario)
    {
        <div style="position: absolute; bottom: 0" id="divAvaliacao">
            <h5 style="display: inline-block">
                Avalie esse vídeo
            </h5>
            @{Int32 noAvUsuario = ViewBag.noAvUsuario;}
            <label>
                @Html.RadioButton("rbtAvaliacao", 1, (noAvUsuario == 1), new { @onclick = "rtbAvaliacao_Click($(this))", @class = "rbtnAvaliacaoAv1" })
                <span>1</span>
            </label>
            <label>
                @Html.RadioButton("rbtAvaliacao", 2, (noAvUsuario == 2), new { @onclick = "rtbAvaliacao_Click($(this))", @class = "rbtnAvaliacaoAv2" })
                <span>2</span>
            </label>
            <label>
                @Html.RadioButton("rbtAvaliacao", 3, (noAvUsuario == 3), new { @onclick = "rtbAvaliacao_Click($(this))", @class = "rbtnAvaliacaoAv3" })
                <span>3</span>
            </label>
            <label>
                @Html.RadioButton("rbtAvaliacao", 4, (noAvUsuario == 4), new { @onclick = "rtbAvaliacao_Click($(this))", @class = "rbtnAvaliacaoAv4" })
                <span>4</span>
            </label>
            <label>
                @Html.RadioButton("rbtAvaliacao", 5, (noAvUsuario == 5), new { @onclick = "rtbAvaliacao_Click($(this))", @class = "rbtnAvaliacaoAv5" })
                <span>5</span>
            </label>
        </div>
    }}
</div>

CoeusProject/Views/Video/_VideosLeftPartial.cshtml
@model CoeusProject.Models.Usuario
@using Kendo.Mvc.UI
@using CoeusProject.Models
@using CoeusProject.Facade
@{
    Layout = null;
    Usuario usuarioLogado = AccountFacade.GetLoggedInUser();
}

<script>
    var idDonoVideo = '@Model.IdUsuario';
    function gridVideos_Data() {
        return { idUsuario: idDonoVideo };
    }

    function btnNovoVideo_Click(e) {
        bindCenterPartial('@Url.Action("CreatePartial","Video")');
    }

    $(document).ready(function () {
        $("#gridVideos").on("dblclick", "tr.k-state-selected", function () {
            var grid = $("#gridVideos").data("kendoGrid");
            var selectedItem = grid.dataItem(grid.select());
            EditVideo(selectedItem.IdVideo);
        });
    })

    function EditVideo(idVideo) {
        $('#divContent').load('@Url.Action("EditPartial", "Video")', { idVideo: idVideo });
    }

    function gridVideos_DataBound(e) {
        var data = this.dataSource.data();
        $(data).each(function () {
            $('#nmObjeto-' + this.IdVideo).kendoTooltip({
                position: 'right',
                content: '<div style="font-size: 7pt">' +
                        ((this && this.Objeto && this.Objeto.TxDescricao) ? this.Objeto.TxDescricao : '') +
                        '</div>'
            });
        });

    }
</script>
@{if (usuarioLogado.IdUsuario == Model.IdUsuario)
{
    <div style="text-align: left">
        @(Html.Kendo().Button()
        .Name("btnNovoVideo")
        .Content("Novo Vídeo")
        .HtmlAttributes(new { @type = "button", @style = "width: 100%" })
        .Events(e => e.Click("btnNovoVideo_Click")))
    </div>
}}

@(Html.Kendo().Grid<CoeusProject.Models.Video>()
    .Name("gridVideos")
    .DataSource(dt => dt.Ajax()
        .Read(
            r => r.Action("AjaxReadVideos", "Video")
            .Data("gridVideos_Data")
        )
        .Model(model => model.Id(m => m.IdVideo))
    )
    .Columns(c =>
    {
        c.Bound(m => m.Objeto.NmObjeto).Title("<div style='margin: 0; padding: 0; width: 185px; overflow: hidden'>Vídeos de " + Model.NmPessoa + "</div>")
            .Width(198).HtmlAttributes(new { @style = "width: 198px" })
            .ClientTemplate("<div id='nmObjeto-#=IdVideo#'>#=Objeto.NmObjeto#</div>");
    })
    .Events(e => e.DataBound("gridVideos_DataBound"))
    .Selectable(select => select.Mode(GridSelectionMode.Single))
    .HtmlAttributes(new { @style = "font-size: 8pt; width: 198px" })
)