CoeusProject/Models/Grupo.cs
using CoeusProject.Facade;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CoeusProject.Models
{
    public class Grupo
    {
        [Key]
        public Int32 IdGrupo { get; set; }

        [DisplayName("Nome do Grupo")]
        [Required(ErrorMessage = "O nome do grupo é obrigatório")]
        [StringLength(512, MinimumLength = 1, ErrorMessage = "O nome do grupo deve conter entre 1 e 100 caracteres")]
        public String NmGrupo { get; set; }

        public virtual ICollection<Usuario> Usuarios { get; set; }

        public virtual ICollection<Mensagem> Mensagens { get; set; }

        [ForeignKey("Objeto")]
        public Int32? IdObjeto { get; set; }
        public virtual Objeto Objeto { get; set; }

        [ForeignKey("Salt")]
        public Int32 IdSalt { get; set; }
        public virtual Salt Salt { get; set; }

        public Grupo Encrypt(CoeusProjectContext Context = null)
        {
            if (this.Salt == null)
            {
                if (Context == null)
                {
                    Context = new CoeusProjectContext();
                }
                this.Salt = Context.Salt.Where(s => s.IdSalt == this.IdSalt).FirstOrDefault();
            }

            this.NmGrupo = SecurityFacade.Encrypt(this.NmGrupo, this.Salt.BtSalt);
            return this;
        }

        public Grupo Decrypt(CoeusProjectContext Context = null)
        {
            if (this.Salt == null)
            {
                if (Context == null)
                {
                    Context = new CoeusProjectContext();
                }
                this.Salt = Context.Salt.Where(s => s.IdSalt == this.IdSalt).FirstOrDefault();
            }

            this.NmGrupo = SecurityFacade.Decrypt(this.NmGrupo, this.Salt.BtSalt);
            return this;
        }
    }
}

CoeusProject/Controllers/GrupoController.cs
using CoeusProject.Facade;
using CoeusProject.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace CoeusProject.Controllers
{
    public class GrupoController : Controller
    {
        CoeusProjectContext _context = new CoeusProjectContext();
        public ActionResult CreatePartial()
        {
            return View("_GrupoEditPartial", new Grupo());
        }

        public ActionResult EditPartial(Int32 IdGrupo)
        {
            Grupo grupo = _context.Grupos.Where(g=>g.IdGrupo == IdGrupo).FirstOrDefault();
            return View("_GrupoEditPartial", grupo);
        }

        public ActionResult GetGrupoUsuariosList(Int32 IdGrupo)
        {
            return Json(_context.Grupos.Where(g=>g.IdGrupo == IdGrupo).Include(g=>g.Usuarios)
                .FirstOrDefault().Usuarios.Decrypt().Select(u=>new
                {
                    IdUsuario = u.IdUsuario,
                    NmPessoa = u.NmPessoa,
                    NmFoto = u.NmFoto,
                    NmThumbFoto = u.NmThumbFoto
                }));
        }

        [HttpPost]
        public ActionResult Create(String nmGrupo, List<Usuario> usuarios)
        {
            try
            {
                if (String.IsNullOrEmpty(nmGrupo))
                {
                    throw new Exception("O nome do grupo é obrigatório");
                }

                if (usuarios == null || usuarios.Count() == 0)
                {
                    throw new Exception("É necessário selecionar algum usuário para o grupo");
                }

                Grupo grupo = new Grupo
                {
                    NmGrupo = nmGrupo,
                    Usuarios = new List<Usuario>(),
                    Salt = Salt.GetSalt()
                };

                foreach (Usuario usuario in usuarios)
                {
                    Usuario grupoUser = _context.Usuarios.Where(u => u.IdUsuario == usuario.IdUsuario).FirstOrDefault();
                    if (grupoUser == null || grupo.Usuarios.Contains(grupoUser)) continue;

                    grupo.Usuarios.Add(grupoUser);
                }

                Usuario usuarioLogado = AccountFacade.GetLoggedInUser();
                if (grupo.Usuarios.Where(u => u.IdUsuario == usuarioLogado.IdUsuario).Count() == 0)
                {
                    grupo.Usuarios.Add(_context.Usuarios.Where(u => u.IdUsuario == usuarioLogado.IdUsuario).FirstOrDefault());
                }

                grupo.Encrypt();
                _context.Grupos.Add(grupo);
                _context.SaveChanges();

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotAcceptable, ErrorFacade.GetErrorMessage(ex));
            }
        }

        [HttpPost]
        public ActionResult Edit(Int32 idGrupo, String nmGrupo, List<Usuario> usuarios)
        {
            try
            {
                Grupo grupo = _context.Grupos.Where(g => g.IdGrupo == idGrupo).Include(g=>g.Usuarios).FirstOrDefault().Decrypt();
                if (grupo == null)
                {
                    throw new Exception("Grupo inexistente");
                }

                List<Usuario> usuariosGrupo = grupo.Usuarios.ToList();

                if (String.IsNullOrEmpty(nmGrupo))
                {
                    throw new Exception("Nome inválido para o grupo");
                }

                if (usuarios == null || usuarios.Count() == 0)
                {
                    throw new Exception("É necessário selecionar algum usuário para o grupo");
                }

                grupo.NmGrupo = nmGrupo;

                for (int i = usuariosGrupo.Count() - 1; i >= 0; i--)
                {
                    if (usuarios.Where(u => u.IdUsuario == usuariosGrupo[i].IdUsuario).Count() == 0)
                    {
                        grupo.Usuarios.Remove(usuariosGrupo[i]);
                    }
                }

                for (int i = usuarios.Count() - 1; i >= 0; i--)
                {
                    if (usuariosGrupo.Where(ug => ug.IdUsuario == usuarios[i].IdUsuario).Count() == 0)
                    {
                        Int32 idUsuarioAdded = usuarios[i].IdUsuario;
                        grupo.Usuarios.Add(_context.Usuarios.Where(u=>u.IdUsuario == idUsuarioAdded).FirstOrDefault());
                    }
                }

                Usuario usuarioLogado = AccountFacade.GetLoggedInUser();
                if (grupo.Usuarios.Where(u => u.IdUsuario == usuarioLogado.IdUsuario).Count() == 0)
                {
                    grupo.Usuarios.Add(_context.Usuarios.Where(u => u.IdUsuario == usuarioLogado.IdUsuario).FirstOrDefault());
                }

                grupo.Encrypt();
                _context.Entry(grupo).State = EntityState.Modified;
                _context.SaveChanges();
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotAcceptable, ErrorFacade.GetErrorMessage(ex));
            }
        }

        public ActionResult GetUserWhereNmPessoaStartsWith(String nmPessoa)
        {
            if (String.IsNullOrEmpty(nmPessoa))
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }

            List<Usuario> usuarios = _context.Usuarios.ToList();
            List<Usuario> usuariosRet = new List<Usuario>();

            foreach (Usuario usuario in usuarios)
            {
                Usuario retUsuario = usuario.Decrypt();
                if (retUsuario.NmPessoa.ToUpper().StartsWith(nmPessoa.ToUpper()) ||
                    retUsuario.TxEmail.ToUpper().StartsWith(nmPessoa.ToUpper()))
                {
                    usuariosRet.Add(retUsuario);
                }
            }

            if (usuarios == null || usuarios.Count() == 0)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }

            return Json(usuariosRet.Select(u => new
            {
                IdUsuario = u.IdUsuario,
                NmPessoa = u.NmPessoa,
                TxEmail = u.TxEmail,
                NmFoto = u.NmFoto,
                NmThumbFoto = u.NmThumbFoto
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetGrupoWhereNmGrupoStartsWith(String nmGrupo)
        {
            Usuario usuarioLogado = AccountFacade.GetLoggedInUser();

            List<Grupo> grupos = _context.Grupos.Where(g => g.Usuarios.Any(u => u.IdUsuario == usuarioLogado.IdUsuario) && g.IdObjeto == null)
                                       .Include(g => g.Usuarios).Decrypt();

            if (!String.IsNullOrEmpty(nmGrupo))
            {
                grupos = grupos.Where(g => g.NmGrupo.StartsWith(nmGrupo)).ToList();
            }

            if (grupos == null)
            {
                return Json("", JsonRequestBehavior.AllowGet);
            }

            return Json(grupos.Select(g => new
            {
                IdGrupo = g.IdGrupo,
                NmGrupo = g.NmGrupo
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddObjectGroup(Int32 idObjeto)
        {
            Int32 idUsuarioLogado = AccountFacade.GetLoggedInUser().IdUsuario;
            List<Grupo> gruposFilter = _context.Grupos.Where(g => g.IdObjeto == null &&
                                        g.Usuarios.Any(u => u.IdUsuario == idUsuarioLogado)).OrderBy(g => g.NmGrupo).Decrypt();

            Usuario usuarioLogado = AccountFacade.GetLoggedInUser();

            Grupo grupoObj = null;

            while (grupoObj == null)
            {
                grupoObj = _context.Grupos.Include(g => g.Usuarios).Include(g=>g.Salt)
                            .Where(g => g.IdObjeto != null && g.IdObjeto == idObjeto).FirstOrDefault();

                _context = new CoeusProjectContext();
            }

            gruposFilter.Add(grupoObj.Decrypt());

            return Json(gruposFilter.Select(s => new Grupo
            {
                IdGrupo = s.IdGrupo,
                NmGrupo = s.NmGrupo
            }));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CoeusProject/Views/Grupo/_GrupoEditPartial.cshtml
@using Kendo.Mvc.UI
@model CoeusProject.Models.Grupo
@{Layout = null;}

<script>
    function btnCreateGrupo_Click(e) {
        var idGrupo = '@((Model == null || Model.IdGrupo == 0) ? 0 : Model.IdGrupo)';

        if (idGrupo && parseInt(idGrupo)) {
            $.ajaxPost('@Url.Action("Edit","Grupo")', {
                idGrupo: idGrupo,
                nmGrupo: $('#NmGrupo').val(),
                usuarios: lstSelectedUsers
            },
            null,
            function () {
                kendoAlert('Grupo Editado');
                $('#wndGroup').data('kendoWindow').close();
                $('#cmbNmGrupo').data('kendoComboBox').dataSource.read();
            });
        } else {
            $.ajaxPost('@Url.Action("Create","Grupo")', {
                nmGrupo: $('#NmGrupo').val(),
                usuarios: lstSelectedUsers
            },
            null,
            function () {
                kendoAlert('Grupo criado');
                $('#wndGroup').data('kendoWindow').close();
                $('#cmbNmGrupo').data('kendoComboBox').dataSource.read();
            });
        }
    }

    function btnCancelGrupo_Click(e) {
        $('#wndGroup').data('kendoWindow').close();
    }
</script>

@using (Html.BeginForm("Create", "Grupo", FormMethod.Post, new { @id = "frmGrupo", @style = "overflow: hidden" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    if (Model != null && Model.IdGrupo > 0)
    {
        Html.HiddenFor(m => m.IdGrupo);
    }

    <div class="divInline">
        <div>
            @Html.TextBoxFor(m => m.NmGrupo, new { @class = "k-textbox inputInline", @placeholder = "Nome do grupo", @style = "width: 90%" })
            @Html.ValidationMessageFor(m => m.NmGrupo)
        </div>

        <div id="divUsers">
            @Html.Partial("_SearchUsersPartial", ((Model == null || Model.IdGrupo == 0) ? 0 : Model.IdGrupo))
        </div>

        <div id="divActions" class="k-header" style="position: absolute; left: 0; right:0; bottom:0;">
            @(Html.Kendo().Button()
                .Name("btnCreateGrupo")
                .Content("<img src='/Images/saveAs.png' alt='Create'/>")
                .HtmlAttributes(new { @style = "float: left", @type = "button" })
                .Events(e => e.Click("btnCreateGrupo_Click"))
            )

            @(Html.Kendo().Button()
                .Name("btnCancelGrupo")
                .Content("<img src='/Images/close.png' alt='Cancel'/>")
                .HtmlAttributes(new { @style = "float: left", @type = "button" })
                .Events(e => e.Click("btnCancelGrupo_Click"))
            )
        </div>
    </div>
}

CoeusProject/Views/Grupo/_SearchUsersPartial.cshtml
@model int
@using Kendo.Mvc.UI
@{
    Layout = null;
}

<style>
    .showUser {
        float: left;
        width: 220px;
        height: 40px;
        margin: 0;
        padding: 5px;
        cursor: pointer;
    }

        .showUser img {
            float: left;
            width: 32px;
            height: 32px;
        }

        .showUser h3 {
            margin: 0;
            padding: 5px 0 0 5px;
            font-size: .9em;
            overflow: hidden;
            font-weight: normal;
            float: left;
            max-width: 100px;
        }

    .searchUser {
        display: inline-block;
        height: 50px;
        text-align: left;
        margin: 0;
        padding: 0;
    }

        .searchUser > img {
            float: left;
            width: 32px;
        }

        .searchUser > span {
            display: inline-block;
            height: 32px;
            margin: 0;
            padding: 0;
            line-height: 1em;
            font-size: 8pt;
        }

        .searchUser > h4 {
            display: inline-block;
            margin: 0;
            padding: 0;
        }
</style>

<script type="text/x-kendo-tmpl" id="tmplUser">
    <div class="showUser" data-id="#=IdUsuario#">
        <img src="/User_Data/#=NmThumbFoto#" alt="#=NmPessoa# image" />
        <h3>#=NmPessoa#</h3>
        <button type="button" class="k-button"
                style="float: right; margin: 0; padding: 0 3px 0 3px; font-size: 8pt; font-weight: bold"
                onclick="btnRemoveUser_Click()">
            X
        </button>
    </div>
</script>

<script type="text/x-kendo-tmpl" id="tmplSearchUser">
    <div class="searchUser">
        <span>
            <img src='/User_Data/#=NmThumbFoto#' alt='#=NmPessoa#' />
        </span>
        <span>
            <h4>#=NmPessoa#</h4>
            #=TxEmail#
        </span>
    </div>
</script>

<script>
    var lstSelectedUsers = [];

    $(document).ready(function () {
        var idGrupo = '@Model';
        if (idGrupo && parseInt(idGrupo)) {
            $.ajax({
                url: '@Url.Action("GetGrupoUsuariosList","Grupo")',
                type: 'POST',
                data: { IdGrupo: idGrupo },
                success: function (data) {
                    lstSelectedUsers = data;
                    BindLstUsers();
                }
            });
        }
    });

    function lstFindUsers_Change(e) {
        var a = e;
        var b = a;
    }

    function cmbNmPessoa_AdditionalData(e) {
        return {
            nmPessoa: $('#cmbNmPessoa').data('kendoComboBox').text()
        };
    }

    function cmbNmPessoa_Select(e) {
        var dataItem = this.dataItem(e.item.index());
        lstSelectedUsers.push({
            IdUsuario: dataItem.IdUsuario,
            NmPessoa: dataItem.NmPessoa,
            NmFoto: dataItem.NmFoto,
            NmThumbFoto: dataItem.NmThumbFoto
        });

        BindLstUsers();
    }

    function BindLstUsers() {
        var dataSource = new kendo.data.DataSource({ data: lstSelectedUsers });
        $('#lstUsers').data('kendoListView').setDataSource(dataSource);
    }

    function btnRemoveUser_Click() {
        var selectedUser = $('#lstUsers').data('kendoListView').select();
        lstSelectedUsers = $.grep(lstSelectedUsers, function (user, index) {
            return user.IdUsuario != selectedUser.data('id');
        });
        BindLstUsers();
    }
</script>

@(Html.Kendo().ComboBox().Name("cmbNmPessoa")
    .DataTextField("NmPessoa")
    .DataValueField("IdPessoa")
    .TemplateId("tmplSearchUser")
    .Suggest(true)
    .MinLength(2)
    .Height(400)
    .DataSource(ds => ds.Read(read => read.Action("GetUserWhereNmPessoaStartsWith", "Grupo")
        .Data("cmbNmPessoa_AdditionalData")).ServerFiltering(true))
    .Filter(FilterType.StartsWith)
    .AutoBind(false)
    .Events(e => e.Select("cmbNmPessoa_Select"))
    .HtmlAttributes(new { @placeholder = "Buscar por nome ou e-mail", @style = "width: 90%" })
)

Pessoas No Grupo
<div id="divGrupoUsuarios" style="height: 178px; width: 500px; overflow: auto">
    @(Html.Kendo().ListView(new List<dynamic>()).Name("lstUsers")
        .ClientTemplateId("tmplUser")
        .TagName("div")
        .DataSource(ds => ds.Custom())
        .Selectable(select => select.Mode(ListViewSelectionMode.Single))
    )
</div>